---
title: "ReACTIVATE"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    source_code: "https://github.com/samarthaFFM/Reactivate_dashboard"
    theme: flatly #lumen, yeti, flatly
    vertical_layout: fill
    navbar:
      - { title: "About", 
          href: "https://react-now.com/",
          align: right }
    social: [ "menu" ]
    css: styles.css
    logo: logo.png
runtime: shiny
---

```{r setup, include=FALSE}

library(flexdashboard)
library(tidyverse)
library(shiny)        #renderPlot, renderTable, sliderInput
library(shinyWidgets) #radioGroupButtons
library(flexdashboard)
library(readr)
library(DT)
library(tidyverse)
library(lubridate)
library(plotly)
library(ggrepel)
library(ggpubr)				

```

```{r data input}

#read output datasets from DB

#read transaction datasets if necessary 

data_input = read.csv('./Product_datasheets.xlsx - DB_output_1.csv')

raw_data = data_input
```

Dashboard for supermarket employees {data-icon="fa-user-shield"}
=====================================

LeftColumn {.sidebar data-width=200} 
-------------------------------------
Filter the data:

```{r filters}
# You can make this sidebar global by putting it ahead of Tab 1
# below are 2 input options: a gorup of buttons, and a slider

#selected_range = as.numeric(data$Discount_predictions[!is.na(data$Discount_predictions)])


# add numeric input to filter remaining fresh days 

numericInput(
  inputId="Freshdays",
  label="Remaining FreshDays",
  value = 7,
  min = 0,
  max = 100,
  step = 1,
  width = NULL
)

# add checkbox to select category 

checkboxGroupInput(
  inputId="Category",
  label="Select by Category",
  choices = c("Fruit", "Meat","Yogurt","Drink"),
  selected = c("Fruit", "Meat","Yogurt","Drink")
)


# add checkbox to select location ID

checkboxGroupInput(
  inputId="Location",
  label="Select by Location",
  choices = c("Fridge", "Shelf"),
  #plz note "Fridges" instead of FRI124(fridge+number in datasheet) is shown here.
  #pay attention when filtering the datasheet, or just simply revise location into fridges/shelves in datasheet
  selected = c("Fridge", "Shelf")
)
# 

# for selecting discount

# radioGroupButtons( # for categorical variables
#   inputId = "Discount_percent", # this will allow the selection to be referenced as input$cyl
#   label = "Select Discount", # NULL if you don't want a header
#   choiceNames = c("10%", paste(dataframe_filtered$Discount_predictions*100,'%')), # can use paste, etc to make nicer display
#   choiceValues = c("10%", paste(dataframe_filtered$Discount_predictions*100,'%')), # values in the data, need to line up with above
#   justified = TRUE, # will fill the width of the container it sits in (sidebar)
#   status = "primary"
# )


disc_range = seq(from=0, to=100, by=100)

sliderInput(
  inputId = "Discount_range", # referenced as input$displ
  label = "Select discount label",
  value = disc_range, # default selection, you can move the range around
  min = 0, #(min(disc_range)),
  max = 100, #(max(disc_range)),
  step = 5
)




# This will build a dataframe to use throughout the dashboard. To reference this dataframe, you will need to be in some reactive element ex: renderText({nrow(use_data())}). This is essentially a function and so you will need to use parentheses at the end like this: use_data()

#item is the selected product row or all items of that product? 


dataframe_filtered <- reactive({
        dataframe <- raw_data %>% filter(Freshdays <= input$Freshdays) %>% filter(Category %in% input$Category) 
        dataframe <- dataframe %>% filter(Location %in% input$Location) %>% filter(Discount_predictions <= max(input$Discount_range)/100 & Discount_predictions >= min(input$Discount_range)/100)
        dataframe
})

dataframe_filtered_without_days <- reactive({
        dataframe <- raw_data %>% filter(Category %in% input$Category) 
        dataframe <- dataframe %>% filter(Location %in% input$Location) %>% filter(Discount_predictions <= max(input$Discount_range)/100 & Discount_predictions >= min(input$Discount_range)/100)
        dataframe
})



```

> **Descripton**

ReActivate provides discount predictions for all products automatically using our cutting-edge AI. You can choose and print the discount label that you want! 

**Line chart reference** - *Product type vs time*

**Red**: Check and print discount immediately

**Green**: Ok! Approaching expiry

**Label**: Number of days till expiry

ProductTableColumn {data-width=350}
-----------------------------------------------------------------------
### Filtered Product List

```{r table}
#display top 10 items that require attention table here

renderTable({dataframe_filtered() %>% arrange(Priority_clusters) %>% select(-c(Batch.code, Priority_clusters, Discount_predictions)) 
  })
#datatable(reactive({dataframe_filtered() %>% arrange(Priority_clusters)}))																   

# #this will display a top 10 table that is filtered based on the selections above
# renderTable({ # use {...} for the output (an expression)
#     use_data() %>%
#       arrange(desc(hwy)) %>%
#       slice(1:10) %>%
#       mutate(Rank = row_number()) %>%
#       select(Rank, year, manufacturer, model, trans, hwy, fl, class)
#   },
#   # renderTable takes additional arguments after the {...}
#   spacing = "xs",
#   align = "l",
#   bordered = TRUE
# )

```


### Expiry date indicator: Chart for number of days till the expiry of product

```{r}

#LineDiagram {data-width=250}

# renderPlot({dataframe_filtered() %>% arrange(Priority_clusters) %>%
#   ggplot(aes(x = Freshdays, y = Product_ID, group = Priority_clusters)) +
#   geom_line() + 
#   geom_point() +
#   ylab('Product ID') +
#   xlab('days till expiry')})

today = as.Date('2020-12-07')

renderPlot({dataframe_filtered() %>% mutate(today = rep(today, length(Freshdays)))  %>% select(Product_ID, Description, today, Expiration, Freshdays,Category, Priority_clusters) %>%  mutate(Expiration_date = as.Date(Expiration)) %>% gather(date,time, today, Expiration_date)  %>%
  ggplot(aes(x = time, y = Description )) +
  geom_line(aes(color= factor(Priority_clusters), size=3)) + 
  ylab('Product') +
  xlab('Days till expiry') + geom_label_repel(aes(label = Freshdays),
                  box.padding   = 0.35, 
                  point.padding = 0.5,
                  segment.color = 'grey50')  + geom_point(aes(size=3)) + scale_color_manual(values=c("#FF0000", "#FF0000", "#008000")) + guides(color = FALSE, size = FALSE) + theme_bw() +  theme(axis.text.x=element_text(size=13, angle=45, hjust=1),axis.text.y=element_text(size=13), text = element_text(size=13)) + labs(fill = "Priority")
 })


# line_plot <- dataframe_filtered() %>% arrange(Priority_clusters) %>%
#   ggplot(aes(x = Freshdays, x = Product_ID, group = Priority_clusters)) +
#   geom_line() + 
#   geom_point() +
#   ylab('Product ID') +
#   xlab('days till expiry')

#ggplotly(line_plot)
#line plot to indicate expiry dates of item selected and discount predictions for that item or previous sales with discount to give employee some idea on deciding discount

# renderPlot({ # renderPlot is only required becuase we are referencing someting reactive: use_data(). Otherwise we could just use ggplot(raw_data,...)
#   ggplot(use_data(), aes(displ, hwy)) +
#     geom_smooth(color = "grey65") +
#     geom_point(aes(color = factor(cyl))) +
#     ylim(0, 45) +
#     labs(color = "Cylinder") +
#     theme(legend.position = "bottom")
# })

```


RightColumn {data-width=100}
-----------------------------------------------------------------------

### Today's workload
```{r}
renderGauge({
  value <- dataframe_filtered() %>% filter(Freshdays <= 0) %>% nrow()
  min <- 0
  max <- dataframe_filtered() %>% filter(Freshdays < 7) %>% nrow()
  step <- (max - min) / 3
  gauge(value, min = min, max = max, symbol = '', 
        gaugeSectors(success = c(min-0.5, step-0.5), warning = c(step, 2*step-0.5), 
                     danger = c(2*step, max+0.5)
  ))
})
```

<!-- ### Expired or expiring next -->
<!-- ```{r all products to be checked} -->

<!-- #to do  -->
<!-- #Counter list of products already checked today -->

<!-- renderValueBox({ -->
<!--   valueBox(prettyNum(dataframe_filtered() %>% filter(Freshdays < 7) %>% nrow(),  -->
<!--                      big.mark = ','), icon = 'fa-walking') -->
<!-- }) -->
<!-- ``` -->

### Expired today - To be thrashed
```{r expired}

#Counter list of products to be checked today
renderValueBox({
  valueBox(prettyNum(dataframe_filtered() %>% filter(Freshdays <= 0) %>% nrow(), 
                     big.mark = ','), icon = 'fa-dizzy', color = 'danger')
})
```



### Expires within a week - Check soon!
```{r week 1}

#Counter list of products to be checked today
renderValueBox({
  valueBox(prettyNum(dataframe_filtered() %>% filter(Freshdays > 0 & Freshdays < 7) %>% 
                       nrow(), big.mark = ','), 
           icon = 'fa-exclamation-triangle', color = 'warning')
})

```

### All good products
```{r good for more than a week}

renderValueBox({
  valueBox(prettyNum(dataframe_filtered_without_days() %>% filter(Freshdays >= 7) %>% nrow(), 
                     big.mark = ','), icon = 'fa-seedling', color = 'info')
})

```

### Proportion of good products
```{r}
renderGauge({
  min <- 0
  max <- 100
  total <- (dataframe_filtered_without_days() %>% nrow())
  value <- (dataframe_filtered_without_days() %>% filter(Freshdays >= 7) %>% 
                    nrow()) / total
  value <- ifelse(total == 0, 100, round(value * 100, digits = 1))
  gauge(value, min = min, max = max, symbol = '%', gaugeSectors(
    success = c(80, max+0.5), warning = c(40, 79), danger = c(min-0.5, 39)
  ))
})
```

### Print Discount offer 

Print the discount offer label according to the product selected 

```{r print function}
x = raw_data[which(raw_data$Discount_predictions != 0),]
radioGroupButtons( # for categorical variables
  inputId = "Print_Discount_percent", # this will allow the selection to be referenced as input$cyl
  label = NULL, # NULL if you don't want a header
  choiceNames = c("None", paste(unique(x$Discount_predictions*100),'%')), # can use paste, etc to make nicer display
  choiceValues = c("None", paste(unique(x$Discount_predictions*100),'%')), # values in the data, need to line up with above
  justified = TRUE, # will fill the width of the container it sits in (sidebar)
  status = "primary"
)
```

Inventory {data-icon="fa-columns" data-orientation=rows}
=====================================

LeftColumn {.sidebar data-width=200} 
-------------------------------------
```{r}
textInput(inputId = "Search", label = "", value = "", width = NULL, placeholder = "Search for...")
```


MainColumn {data-width=500} 
-------------------------------------
### Table of all products
```{r}
dataframe_search <- reactive({
  raw_data
  #dataframe <- raw_data %>% filter(findDescription %in% input$Search)
  #dataframe
})

renderTable({dataframe_search() %>% arrange(Product_ID)})
```


